### ISSUE TITLE
Support for Federated Rule Groups

### ISSUE THREAD

**Issue by paulojmdias** [fgouteroux/terraform-provider-mimir#13]
Hi,

Is there any opening to support Federated Rule Groups with this provider? I think will be nice to allow evaluation rules across multiple tenants.

Context: https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/ruler/#federated-rule-groups

Thanks

**Comment by fgouteroux** [comment]
Hi @paulojmdias,

Yes, good spot, just implemented in [v0.1.6](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.1.6).
I added a simple acc test to check but I would appreciate a feedback about this.

**Comment by paulojmdias** [comment]
Wow! a feature in 3 hours! 👏 

Many thanks, @fgouteroux, I will test it. But everything seems ok
