### ISSUE TITLE
Preservation of Formatting in Expressions

### ISSUE THREAD

**Issue by gerrywd** [fgouteroux/terraform-provider-mimir#14]
Hello,

Currently, when using the Mimir Terraform provider to write expressions, white-space characters and newlines seem to be mostly stripped out. This leads to the resulting expressions being quite difficult to read, especially when they have numerous label selectors or fields that were originally written on separate lines for better readability.

For example, consider the following expression:

```ruby
sum without (
  job,
  instance,
  kubernetes_pod_name,
  kubernetes_namespace,
  ingress_controller_name,
  host,
  method,
  status_code
) (
  rate(
    http_request_duration_microseconds_sum{
      status_code=~"5.*",
      method="POST",
      kubernetes_namespace="production",
      ingress_controller_name="nginx-ingress",
      job="http-service",
      instance="us-east-1"
    }[5m]
  )
) > 10
```

When applying, it becomes:

```ruby
sum without (job, instance, kubernetes_pod_name, kubernetes_namespace, ingress_controller_name, host, method, status_code) (
    rate(
        http_request_duration_microseconds_sum{instance="us-east-1",job="http-service",method="POST",kubernetes_namespace="production",ingress_controller_name="nginx-ingress",status_code=~"5.*"}[5m]
    )
)
>
    10
 ```

As you can see, the second version is harder to read and understand. Is there a possibility to preserve the original formatting? This would significantly improve the readability and maintainability of complex expressions.

The relevant part of the code appears to be in shared.go, as per the below link:

https://github.com/fgouteroux/terraform-provider-mimir/blob/78f3edeffad035f4ff32eaea0b623b679e1e1d54/mimir/shared.go#L129C33-L129C41

Any insights or potential workarounds for this issue would be greatly appreciated.

Thank you.

**Comment by fgouteroux** [comment]
Hello @gerrywd, yes the formatting of promQL expression have been introduced in [v0.1.4](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.1.4). I understand your use case and I think that this formatting should be a provider parameter, so you will be able to choose if you want to enable this feature or not.

**Comment by fgouteroux** [comment]
@gerrywd the [v0.1.7](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.1.7) version should resolve your issue.

**Comment by gerrywd** [comment]
Wow, that was fast! Thank you so much! 🕺
