### ISSUE TITLE
Can't find a way to set  times  in time_interval in hours  

### ISSUE THREAD

**Issue by rayuduc** [fgouteroux/terraform-provider-mimir#17]
Hello,
Thanks for provider.  
Is there anyway way we can set hours, provider documentation says start_minutes and end_minutes (Data type: number). But alertmanager documentation start_time and end_time. Can you please guid here ?
 
Something like 

```
  times {
        start_time = 3  # 3:00 AM MDT
        end_time   = 21 #  9:00 PM MDT 
      }
```

Alertmanager times format:

```
 times:
    - start_time: HH:MM
      end_time: HH:MM
```

terraform time_interval configuration getting Error. 

ERROR: ` Error: Cannot update alertmanager config unexpected response code '400': error validating Alertmanager config: configuration provided is empty, if you'd like to remove your configuration please use the delete configuration endpoint`
```
time_interval {
    name = "test_mute_window_60min"
    time_intervals {
      location = "America/Denver"
      weekdays {
        begin = 0
        end   = 5
      }
      times {
        start_minute = 3
        end_minute   = 21
      }
    }
  }
```

**Comment by fgouteroux** [comment]
@rayuduc I will have a look, this is strange. Maybe missing start_hours or rewrite the format to match hh:mm

**Comment by fgouteroux** [comment]
From the alertmanager timeinterval code: 

```
// TimeRange represents a range of minutes within a 1440 minute day, exclusive of the End minute. A day consists of 1440 minutes.
// For example, 4:00PM to End of the day would Begin at 1020 and End at 1440.
```

But it will be more simple to keep the same format than alertmanager yaml config.

**Comment by fgouteroux** [comment]
@rayuduc with the last release [v0.1.9](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.1.9), you could do it like this:
```
time_interval {
  name = "test_mute_window_60min"
  time_intervals {
    location = "America/Denver"
    weekdays {
      begin = 0
      end   = 5
    }
    times {
      start_time = "03:00"
      end_time   = "09:00"
    }
  }
}

**Comment by rayuduc** [comment]
Thank you @fgouteroux for the fix.

**Comment by rayuduc** [comment]
Hi @fgouteroux ,
We tried below configuration and terraform getting below error and it looks like location is the issue. 
Cannot update alertmanager config unexpected response code '400': error validating Alertmanager config: configuration provided is empty, if you'd like to remove your configuration please use the delete configuration endpoint

When we tried with UTC, start time is 9 AM  UTC and end time is 3 AM UTC on next day without location and we got different error. 
How we can specify time in next day ?
│ Error: Cannot update alertmanager config unexpected response code '400': error validating Alertmanager config: start time cannot be equal or greater than end time

`time_interval {
  name = "test_mute_window_60min"
  time_intervals {
    location = "America/Denver"
    weekdays {
      begin = 0
      end   = 5
    }
    times {
      start_time = "03:00"
      end_time   = "21:00"
    }
  }
}`

**Comment by fgouteroux** [comment]
@rayuduc Maybe you should add another `time_interval` block like this:
```
resource "mimir_alertmanager_config" "config" {
  time_interval {
    name = "test1"
    time_intervals {
      location = "America/Denver"
      weekdays {
        begin = 0
        end   = 4
      }
      times {
        start_time = "03:00"
        end_time   = "21:00"
      }
    }
  }

  time_interval {
    name = "test2"
    time_intervals {
      location = "America/Denver"
      weekdays {
        begin = 5
        end   = 5
      }
      times {
        start_time = "06:00"
        end_time   = "20:00"
      }
    }

  }
}
```

**Comment by rayuduc** [comment]
Hi @fgouteroux ,
I'm looking for intervals 
Monday to Friday - America/Denver timezone 3AM to 9PM MDT
If its UTC. Monday to Friday  - UTC 9 AM to 3 AM on next day.

**Comment by rayuduc** [comment]
Hi @fgouteroux ,
Can you please help suggest what the best way to implement this ?. Getting terraform error if we use location ** location = "America/Denver"** but not if we define UTC location.

**Comment by rayuduc** [comment]
It appears location is the problem and I can able to create interval in UTC. 
**╷
│ Error: unknown time zone America/Denver**

`  time_interval {
    name = "test_mute_window_60min"
    time_intervals {
      location = "UTC"
      weekdays {
        begin = 1
        end   = 1
      }
      weekdays {
        begin = 2
        end   = 2
      }
      weekdays {
        begin = 3
        end   = 3
      }
      weekdays {
        begin = 4
        end   = 4
      }
      weekdays {
        begin = 5
        end   = 5
      }
      times {
        start_time = "09:00"
        end_time   = "23:59"
      }
      times {
        start_time = "00:00"
        end_time   = "03:00"
      }
    }
  }`

**Comment by fgouteroux** [comment]
@rayuduc what is the OS running mimir ?

**Comment by rayuduc** [comment]
This is in Grafana Cloud; unfortunately, we don't have information about the operating system that Mimir is running on the Grafana side.
prometheus Mimir version is 2.3.x.

**Comment by fgouteroux** [comment]
@rayuduc I trried to reproduce the issue but I got no error with a local environment. It seems that the location has no effect.  Could you give the full terraform config ?

**Comment by fgouteroux** [comment]
@rayuduc with mimir 2.3 I got this 
```
│ Error: Cannot create alertmanager config unexpected response code '400': error validating Alertmanager config: yaml: unmarshal errors:
│   line 24: field location not found in type timeinterval.TimeInterval
```
It works correctly from the 2.4.

**Comment by rayuduc** [comment]
Hi @fgouteroux , Please find the terraform configuration. Getting ** Error: unknown time zone America/Denver**. I see any option to set mimir version for alertmanager datasource. 
```resource "mimir_alertmanager_config" "dev_alerts" {
  provider = mimir.alertmanager
time_interval {
    name = "dev_60min_mute_window"
    time_intervals {
      location = "America/Denver"
      weekdays {
        begin = 1
        end   = 5
      }
      times {
        start_time = "03:00"
        end_time   = "09:00"
      }
    }
  }
  route {
    # How long to initially wait to send a notification for a group
    # of alerts. Allows to wait for an inhibiting alert to arrive or collect
    # more initial alerts for the same group. (Usually ~0s to few minutes.)
    group_wait = "30s"

    # How long to wait before sending a notification about new alerts that
    # are added to a group of alerts for which an initial notification has
    # already been sent. (Usually ~5m or more.)
    group_interval = "5m"

   child_route {
      group_wait          = "30s"
      group_interval      = "5m"
      group_by            = ["..."]
      matchers            = ["email_team=default_email"]
      repeat_interval     = "4h"
      receiver            = "app_team_email_receiver"
      mute_time_intervals = ["dev_60min_mute_window"]
      continue            = true
    }
receiver = "default_email"
}

  receiver {
    name = "app_team_email_receiver"
    email_configs {
      to = "email-xxxx@xxxxx.com" 
      ##headers = {
       # #subject = "{{ template \"custom_email_subject\" . }}"
      ##}
      ##html          = "{{ template \"custom_email_html\" . }}"
      ##send_resolved = true
    ##}
  }
}
```
