### ISSUE TITLE
mimir_alertmanager_config - child routes to inherit global parameters

### ISSUE THREAD

**Issue by shybbko** [fgouteroux/terraform-provider-mimir#26]
when working with https://registry.terraform.io/providers/fgouteroux/mimir/latest/docs/resources/alertmanager_config#child_route I noticed that the child routes seem not to inherit global settings, this unnecessarily complicates the config

example of the current requirements:
```
  route {
    global {
      pagerduty_url = "https://events.pagerduty.com/v2/enqueue"
      resolve_timeout = "5m"
    }
    
    group_by = ["alertname", "instance"]
    group_wait = "10s"
    group_interval = "1m"
    repeat_interval = "1h"
    receiver = "default"

    route {
      group_wait = "10s"
      group_interval = "1m"
      repeat_interval = "1h"
      receiver = "aaa"
    }
    route {
      group_wait = "10s"
      group_interval = "1m"
      repeat_interval = "1h"
      receiver = "bbb"
    }
    route {
      group_wait = "10s"
      group_interval = "1m"
      repeat_interval = "1h"
      receiver = "ccc"
    }
  }
```

example of config with inheriting enabled:
```
  route {
    global {
      pagerduty_url = "https://events.pagerduty.com/v2/enqueue"
      resolve_timeout = "5m"
    }
    
    group_by = ["alertname", "instance"]
    group_wait = "10s"
    group_interval = "1m"
    repeat_interval = "1h"
    receiver = "default"

    route {
      receiver = "aaa"
    }
    route {
      receiver = "bbb"
    }
    route {
      receiver = "ccc"
    }
  }
```

**Comment by fgouteroux** [comment]
Indeed, according to the doc:

> A route block defines a node in a routing tree and its children. Its optional configuration parameters are inherited from its parent node if not set.

This will require to remove default parameters of child route and merge the root route parameters.

**Comment by shybbko** [comment]
Okay, thank you. I will try this and let you know.

**Comment by shybbko** [comment]
I tested things.
In my config I have no parameters such as `group_interval` defined at `child_route` level. So according to the previous post the config parameters should get inherited from the global level:

```
resource "mimir_alertmanager_config" "mimir_alertmanager_main_config" {
  count = var.alertmanager_all_alerts_enabled == true ? 1 : 0

  global {
    pagerduty_url = "https://events.pagerduty.com/v2/enqueue"
    resolve_timeout = "5m"
  }

  route {
    group_by = ["alertname", "instance"]
    group_wait = "10s"
    group_interval = "1m"
    repeat_interval = "1h"
    receiver = "xyz"

    child_route {
      matchers = [
        - "severity = xyz"
        - "team = xyz"
      ]
      receiver = "xyz"
    }
	}
}
```

however they are not inherited:

```
│ Error: Missing required argument
│
│   on alertmanager.tf line 289, in resource "mimir_alertmanager_config" "mimir_alertmanager_main_config":
│  289:     child_route {
│
│ The argument "group_interval" is required, but no definition was found.
```

This behaviour is consistent with provider's docs: https://registry.terraform.io/providers/fgouteroux/mimir/latest/docs/resources/alertmanager_config#child_route

```
Required:
group_interval (String) How long to wait before sending a notification about new alerts that are added to a group of alerts for which an initial notification has already been sent.
```

However in my case I have ~40 child routes, 99% of those do not require their parameters to differ from the global ones. So for the simplicity of the config, can't a change be made for these parameters to actually get inherited from the globals (unless explicitly defined on child routes level)?

**Comment by fgouteroux** [comment]
@shybbko it should be fixed with the https://github.com/fgouteroux/terraform-provider-mimir/pull/29. No need to repeat each param in child_route as it will take them from the route config.

**Comment by shybbko** [comment]
Yup, looks like `v0.2.6` of the provider fixed the issue. Thank you! <3
