### ISSUE TITLE
provider seems not to respect format_promql_expr = true

### ISSUE THREAD

**Issue by shybbko** [fgouteroux/terraform-provider-mimir#28]
I was running the provider `v0.1.5` and wanted to upgrade to a newer version.
In `v0.1.7` the expression formatting was set as optional (default = false) https://github.com/fgouteroux/terraform-provider-mimir/issues/14
So I enabled it according to the docs https://registry.terraform.io/providers/fgouteroux/mimir/latest/docs#format_promql_expr because I didn't want changes to be made to my rules:
```
provider "mimir" {
  ruler_uri          = "https://some_url/prometheus"
  alertmanager_uri   = "https://some_url"
  org_id             = "fake"
  format_promql_expr = true
}
``` 
however, the provider seems not to respect this setting and tries to un-format my rules (no changes made to the code other than the provider upgrade), example:
```
      ~ rule {
          ~ expr   = <<-EOT
              - histogram_quantile(
              -   0.95,
              -   sum by (mode, le) (rate(some_metric[2d]))
              - )
              + histogram_quantile(0.95, sum(rate(some_metric[2d])) by (mode, le))
            EOT
```

I tried two versions: `0.1.7` and `0.2.5`, both behave the same.

**Comment by fgouteroux** [comment]
hi @shybbko could give a full example of resource to be able to reproduce your issue ?

**Comment by shybbko** [comment]
When gathering the code you requested I found a flaw in my logic. I have the main Alertmanager config at one level and then the actual rules are a submodule with another set of provider definitions. I wasn't modifying the latter, hence it was not working.

Thank you for being my rubber duck ;) and apologies for creating the ticket without necessity.
