### ISSUE TITLE
Mimir alertmanager teams config

### ISSUE THREAD

**Issue by fotosidla** [fgouteroux/terraform-provider-mimir#32]
Hello
Nowdays the mimir alertmanager allows define webhook for MSteams can you please add it to integration to provider?
Without this i will allways ends up with error:

`Error: Unsupported block type
│ 
│   on alertmanager.tf line 238, in resource "mimir_alertmanager_config" "alert_routing":
│  238:     msteams_configs {
│ 
│ Blocks of type "msteams_configs" are not expected here.`

Integration in terraform should look like this:
`  receiver {
    name = "fooo"
    msteams_configs {
      webhook_url = "some_webhook_url"
    }
  }`

**Comment by fgouteroux** [comment]
Implemented in https://github.com/fgouteroux/terraform-provider-mimir/pull/37

**Comment by fgouteroux** [comment]
Released in [v1.0.0](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v1.0.0)
