### ISSUE TITLE
V1 api deprecation

### ISSUE THREAD

**Issue by fotosidla** [fgouteroux/terraform-provider-mimir#33]
Hello

Will you plan to update provider to be compatibile with new version of Alertmanager?
https://github.com/grafana/mimir/releases

> Alertmanager deprecated the v1 API. All v1 API endpoints now respond with a JSON deprecation notice and a status code of 410.
All endpoints have a v2 equivalent.
The list of endpoints is:

> <alertmanager-web.external-url>/api/v1/alerts

> <alertmanager-web.external-url>/api/v1/receivers

> <alertmanager-web.external-url>/api/v1/silence/{id}

> <alertmanager-web.external-url>/api/v1/silences

> <alertmanager-web.external-url>/api/v1/status

**Comment by fgouteroux** [comment]
Please see my comment: https://github.com/fgouteroux/terraform-provider-mimir/pull/34
