### ISSUE TITLE
How do I do nested policies more than one layer deep for the notification policies?

### ISSUE THREAD

**Issue by bmhkb4** [fgouteroux/terraform-provider-mimir#40]
As the title asks, how do I do nested policies more than one layer deep for the notification policies?

With [child routes](https://registry.terraform.io/providers/fgouteroux/mimir/latest/docs/resources/alertmanager_config#nested-schema-for-routechild_route), you can nest one route under another, but how would I nest another under that child route?

For example, page for prod alerts, slack for nonprod:

```
route = {
  receiver = "none"
  matchers = [
    severity=critical
  ]
  child_routes = [
    {
      receiver = "none"    
      matchers = [ alertname=nodeDown ]
      child_routes = [
        receiver = "page_out"
        matchers = [ environment=prod ]
       ]
      child_routes = [
        receiver = "slack_out"
        matchers = [ environment=nonprod ]
      ]
    }
}
```

**Comment by bmhkb4** [comment]
i.e. this 
![image](https://github.com/fgouteroux/terraform-provider-mimir/assets/3407663/15943cd8-7135-4a0d-ad8f-3f870763f979)

**Comment by bmhkb4** [comment]
Thanks for your quick response.  I will look at flattening out my configuration.

**Comment by bmhkb4** [comment]
They do it in a rather brute force way on the grafana provider:

https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/notification_policy#nested-schema-for-policypolicypolicypolicymatcher

**Comment by fgouteroux** [comment]
@bmhkb4 it's now possible in release [1.0.3](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v1.0.3)
