### ISSUE TITLE
Error: "rule.0.labels": Invalid Label Name "managed-by". Must match the regex ^[a-zA-Z_][a-zA-Z0-9_]*$

### ISSUE THREAD

**Issue by pulchart** [fgouteroux/terraform-provider-mimir#46]
I noticed label name restriction, not allowing to use "`-`" character.

```
│ Error: "rule.0.labels": Invalid Label Name "managed-by". Must match the regex ^[a-zA-Z_][a-zA-Z0-9_]*$
│ 
│   with mimir_rule_group_recording.node_cpu_seconds_aggregation,
│   on main.tf line 8, in resource "mimir_rule_group_recording" "node_cpu_seconds_aggregation":
│    8:     labels = {
│    9:       managed-by = "terraform",
│   10:     }
```

Is it a Mimir/Loki restriction or just a missing "`-`" char as valid one in validation regex in provider code?

**Comment by fgouteroux** [comment]
Hi @pulchart 

The "-" is not valid from prometheus metric data model: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

So it is not accepted by Mimir, you should use "_" instead.

**Comment by pulchart** [comment]
I see, thank you for clarification!
