### ISSUE TITLE
support for labels in recording rules

### ISSUE THREAD

**Issue by shybbko** [fgouteroux/terraform-provider-mimir#5]
Some Mimir recording rules (ie. https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/rules.yaml#L328) require labels to work properly, however the provider seems not to support those?

When running the following code against the provider (version `0.0.9`)

```
  rule {
    record = "cluster_namespace_deployment_reason:required_replicas:count"
    expr   = "ceil(quantile_over_time(0.99, sum by (cluster, namespace) (cluster_namespace_job:cortex_distributor_received_samples:rate5m)[24h:]) / 240000)"
    labels = {
      deployment = "distributor"
      reason = "sample_rate"
    }
  }
```

the following error appears:

```
│ Error: Unsupported argument
│
│   on ../some_path.tf line 592, in resource "mimir_rule_group_recording" "mimir_rules":
│  592:     labels = {
│
│ An argument named "labels" is not expected here.
```

**Comment by fgouteroux** [comment]
hello @shybbko you right, I totally forget labels in recording rules. Just implemented in [version 0.1.0](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.1.0). Let me know if it's ok.

**Comment by shybbko** [comment]
Thanks @fgouteroux , it works like a charm now.
I also greatly appreciate the blazingly fast support, 30 minutes wait for a fix? That's a premium grade support! <3

**Comment by fgouteroux** [comment]
> Thanks @fgouteroux , it works like a charm now. I also greatly appreciate the blazingly fast support, 30 minutes wait for a fix? That's a premium grade support! <3

I was working on it few hours ago before your issue so the code was fresh in my head ;-)
