### ISSUE TITLE
"mimir_alertmanager_config.this.routes.child_route[*].continue" not persisted

### ISSUE THREAD

**Issue by paulojmdias** [fgouteroux/terraform-provider-mimir#6]
Hi,

Every time that we do a plan and if the value of `continue` is true, they will always try to update without success.

I have tried to check the provider code but I haven't found any reason for this happens. If I upload the same `yaml` configuration with `mimirtool` the `continue` with value `true` will be accepted.

```sh
❯ terraform plan
module.alertmanager_config.mimir_alertmanager_config.this: Refreshing state... [id=dummy]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.alertmanager_config.mimir_alertmanager_config.this will be updated in-place
  ~ resource "mimir_alertmanager_config" "this" {
        id              = "dummy"
        # (2 unchanged attributes hidden)

      ~ route {
            # (5 unchanged attributes hidden)

          ~ child_route {
              ~ continue              = false -> true
                # (8 unchanged attributes hidden)
            }
          ~ child_route {
              ~ continue              = false -> true
                # (8 unchanged attributes hidden)
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by fgouteroux** [comment]
Hello @paulojmdias you right, this regresion is caused by this commit https://github.com/fgouteroux/terraform-provider-mimir/commit/df1a942cacec116ebed800a67825a15f10e2894b. I need to create a dedicated method to flatten child route as it cannot contain continue parameter in root route: https://github.com/prometheus/alertmanager/blob/main/config/config.go#L184-L187

**Comment by paulojmdias** [comment]
Many thanks @fgouteroux. Confirmed, it's fixed 🙏

**Comment by fgouteroux** [comment]
> Many thanks @fgouteroux. Confirmed, it's fixed 🙏 

Thanks for reporting this issue. 😉
