### ISSUE TITLE
ability to export rules to yaml to enable test with promtool

### ISSUE THREAD

**Issue by twotired** [fgouteroux/terraform-provider-mimir#7]
Is there an existing method we can use to convert from .tf to .yaml so that we can run 

`promtool test rules test.yml`

as part of the PR process?

I see you have a tool for mimir2tf. Is a new tool required to do the opposite?

https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/

**Comment by fgouteroux** [comment]
@twotired I added a [mimir2tf reverse mode](https://github.com/fgouteroux/mimir2tf#hcl-to-yaml) in [latest mimir2tf release](https://github.com/fgouteroux/mimir2tf/releases/tag/v0.0.3).

**Comment by fgouteroux** [comment]
If you are using tf modules and not directly resources, you can use [yq](https://github.com/mikefarah/yq) and [hcl2json](https://github.com/tmccombs/hcl2json) and do something like that:
```
hcl2json /tmp/mymodule.tf | jq -Mcr '.module[]' | while read -r content
do
  name=$(jq -Mcr '.[0].name' <<< "${content}")
  rules=$(jq -Mcr '.[0].rules' <<< "${content}")
  json='{"groups":[{"name":"'"${name}"'","rules":'"${rules}"'}]}'
  yq -p json -o yaml . <<< $json | promtool check rules /dev/stdin
done
```
